export const LOGO_ICON = require('@/assets/images/logo.png')
export const BACKGROUND_ICON = require('@/assets/images/loginBackground.png')
export const SPLASH_ICON = require('@/assets/images/splash.png')
export const CANTEEN_IMAGE = require('@/assets/images/canteen.png')
export const HUMBA_IMAGE = require('@/assets/images/humba.jpg')
export const PERSON_ICON = require('../assets/images/person.png')
export const PERSON_BLACK_ICON = require('../assets/images/personBlack.png')
